#!/usr/bin/perl

use strict;
use warnings;
use IO::Socket::PortState qw(check_ports);

my $VERSION = "1.0";
my $HOME = $ENV{HOME};
my $TRACKERSFILE = "$HOME/.trackers";
my @Trackers = ();
my $timeout=5;
my $CurPort=0;
my $DEBUG = "off";	# Set to "on" to enable

print "tracker checker v$VERSION\n";
print "============================\n";

my $CurrentTracker = "";

print "Loading in $HOME/.trackers:\n";
if (! -f $TRACKERSFILE)
{
	print "trackers list not found, running updater:\n";
	system("updatetrackers");
}

my $SawVersion = "";
my $NumTrackers = 0;
open my $file, '<', $TRACKERSFILE or die("Unable to open tracker file: $!");
while(<$file>)
{
	my $CurLine = $_;
	chop($CurLine);
	if ($CurLine eq "")
	{
		next;
	}
	if ($SawVersion eq "")
	{
		print "File version: $CurLine\n";
		$SawVersion = "true";
	}
	else
	{
		#print "Saw tracker: $CurLine\n";
		push (@Trackers, $CurLine);
		$NumTrackers += 1;
	}
}
close $file;

print "Saw $NumTrackers trackers\n";

sub CheckTracker
{
	my %port_hash = (
		tcp => {
			$CurPort => {},
		}
	);

	my $TrackerProtocol = "";
	my $StrippedString = "";

	if (substr($CurrentTracker, 0, 4) eq "http")
	{
		#print "Saw http line\n";
		$TrackerProtocol = "http";
		$StrippedString = substr($CurrentTracker, 7);
		#print "stripped: $StrippedString\n";
	}
	elsif (substr($CurrentTracker, 0, 3) eq "udp")
	{
		if ($DEBUG eq "on")
		{
			print "Saw udp line\n";
		}
		$TrackerProtocol = "udp";
		$StrippedString = substr($CurrentTracker, 6);
		if ($DEBUG eq "on")
		{
			print "stripped: $StrippedString\n";
		}
	}
	$StrippedString = substr($StrippedString, 0, -9);
	print "tracker: $StrippedString - ";

	my ($CurHost, $CurPort)  = split(':', $StrippedString);
        my $host_hr = check_ports($CurHost, $timeout, \%port_hash);
        my $CurStatus = $host_hr->{tcp}{$CurPort}{open} ? "Active" : "Unreachable";
	print "$CurStatus\n";

	if ($DEBUG eq "on")
	{
		my $HostTable = sprintf("%-30s : %-5s : %s", $CurHost, $CurPort, $CurStatus);
		print "$HostTable\n";
	}
}

foreach (@Trackers)
{
	#$TorrentCommand = "$TorrentCommand -t \"$_\"";
	$CurrentTracker = $_;
	if ($DEBUG eq "on")
	{
		print "Checking tracker: $CurrentTracker\n";
	}
	CheckTracker();
}

exit 0;
